#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- hosts: "{{ variable_host | default('anu-local') }}"
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    # Sudo Group Setup
    - name: Make sure we have a 'sudo' group
      group:
        name: sudo
        state: present

    # User + Key Setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ user }}"
        state: present
        groups: sudo, audio
        append: true
        create_home: true
        shell: /bin/bash
        update_password: always
        password: "{{ password|password_hash('sha512') }}"

    - name: Template hosts file
      template:
        src: templates/system/hosts.j2
        dest: /etc/hosts

    - name: Template hostname file
      template:
        src: templates/system/hostname.j2
        dest: /etc/hostname